version: "3.8"

services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: myproject_db
      POSTGRES_USER: django_db_user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    environment:
      SQL_HOST: db
      SQL_PORT: 5432
    env_file:
      - docker/.env.dev
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"
    depends_on:
      - db

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test
    environment:
      SQL_HOST: db
      SQL_PORT: 5432
    env_file:
      - docker/.env.test
    command: poetry run pytest
    ports:
      - "8001:8000"
    depends_on:
      - db

  prod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    environment:
      SQL_HOST: db
      SQL_PORT: 5432
    env_file:
      - docker/.env.prod
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
