version: "3.8"

services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: myproject_db
      POSTGRES_USER: django_db_user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  prod:
    image: registry.digitalocean.com/droplet-name/repo-name:latest
    environment:
      SQL_HOST: db
      SQL_PORT: 5432
    env_file:
      - /home/deployer/.env.prod
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
