name: Continuous Delivery

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DROPLET: droplet-name
  REPO: repo-name
  DROPLET_USER: deployer
  DEPLOY_DIR: /home/${{ env.DROPLET_USER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: registry.digitalocean.com/${{ env.DROPLET }}/${{ env.REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy docker-compose.yml to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ env.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "./docker/docker-compose.yml"
          target: "${{ env.DEPLOY_DIR }}/docker-compose.yml"
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ env.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            docker pull registry.digitalocean.com/${{ env.DROPLET }}/${{ env.REPO }}:latest
            docker-compose -f ${{ env.DEPLOY_DIR }}/docker-compose.yml up -d
